name: vue_study_api
description: A Dart API Client for the Vue Study API.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4
  

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
  test: ^1.19.5

  



