name: vue_study_api
description: A Dart API Client for the Vue Study API.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  freezed: ^1.1.0
  # test: ^1.17.12


  



