name: test_mobile_creonit
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  test_mobile_creonit_repository:
    path: packages/test_mobile_creonit_repository
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.5.1
  logger: ^1.1.0
  flutter_svg: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  # shared_preferences: ^2.0.11
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true  
  assets:
    
    - assets/svg/
    - assets/icon/
    - assets/fonts/
    
    - assets/images/
    - assets/illustrators/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          style: italic



flutter_native_splash:

  color: "#ffffff"
  image: "assets/icon/launch_light_screen_400.png"
  android: true
  ios: true
  web: false      


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  
  remove_alpha_ios: true
