name: test_mobile_creonit_repository
description: A Dart Repository which manages the test mobile creonit domain.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.1
  logger: ^1.1.0
  vue_study_api:
    path: ../vue_study_api

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.1.0
  flutter_test:
    sdk: flutter
